<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class UpdateSchemaChanges extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::table('assignments', function(Blueprint $table){
            $table->dropForeign('assignments_asn_ats_id_foreign');
        });

        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_19_plus` AS select concat(`queue_19_plus`.`reg_first_name`,' ',`queue_19_plus`.`reg_last_name`) AS `Enrollee`,date_format(`queue_19_plus`.`reg_dob`,'%d/%m/%Y') AS `DOB`,ifnull(`queue_19_plus`.`reg_email`,'') AS `Email`,ifnull(`queue_19_plus`.`reg_mob`,'') AS `Mobile No`,cast(`queue_19_plus`.`reg_created_ts` as time) AS `Registration Time`,timediff(now(),`queue_19_plus`.`reg_created_ts`) AS `Waiting Time`,concat('<button data-escalate=\"',`queue_19_plus`.`reg_id`,'\" class=\"secondary button\">','Escalate','</button>') AS `Escalate` from `queue_19_plus`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_active_service_desks` AS select `active_service_desks`.`src_centre_name` AS `Service Desk`,cast(`active_service_desks`.`ats_start_ts` as time) AS `Start Time`,timediff(now(),`active_service_desks`.`ats_start_ts`) AS `Active Time`,concat(`active_service_desks`.`att_first_name`,' ',`active_service_desks`.`att_second_name`) AS `Attendant`,(select `queues`.`que_name` from `queues` where (`queues`.`que_id` = `active_service_desks`.`ats_que_id`)) AS `queue`,concat('<button data-expire=\"',`active_service_desks`.`ats_session_id`,'\" class=\"secondary button\">Expire</button>') AS `action1`,(select if((count(0) > 0),'In Progress',(select group_concat(concat('<button data-uuid=\"',`active_service_desks`.`ats_session_id`,'\" data-switch-queue=\"',`queues`.`que_id`,'\" class=\"secondary button\">',`queues`.`que_name`,'</button>') separator '&nbsp') from `queues` where (`queues`.`que_id` <> `active_service_desks`.`ats_que_id`))) from `switch_queues` where ((`switch_queues`.`swq_ats_session_id` = `active_service_desks`.`ats_session_id`) and isnull(`switch_queues`.`swq_actioned_ts`))) AS `switch queue` from `active_service_desks` order by (select `queues`.`que_name` from `queues` where (`queues`.`que_id` = `active_service_desks`.`ats_que_id`));
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_enrolled` AS select concat(`enrolled`.`reg_first_name`,' ',`enrolled`.`reg_last_name`) AS `ENROLLEE`,date_format(`enrolled`.`reg_dob`,'%d/%m/%Y') AS `DOB`,ifnull(`enrolled`.`reg_email`,'') AS `EMAIL`,ifnull(`enrolled`.`reg_mob`,'') AS `MOBILE NO`,cast(`enrolled`.`asn_created_ts` as time) AS `START TIME`,timediff(`enrolled`.`asn_completed_ts`,`enrolled`.`asn_created_ts`) AS `ENROL TIME`,concat('<button data-revert=\"',`enrolled`.`reg_id`,'\" class=\"secondary button\">Restore</button>') AS `Action` from `enrolled`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_failed_enrollments` AS select concat(`failed_enrollment`.`reg_first_name`,' ',`failed_enrollment`.`reg_last_name`) AS `ENROLLEE`,date_format(`failed_enrollment`.`reg_dob`,'%d/%m/%Y') AS `DOB`,ifnull(`failed_enrollment`.`reg_email`,'') AS `EMAIL`,ifnull(`failed_enrollment`.`reg_mob`,'') AS `MOBILE NO`,cast(`failed_enrollment`.`asn_created_ts` as time) AS `START TIME`,timediff(`failed_enrollment`.`asn_completed_ts`,`failed_enrollment`.`asn_created_ts`) AS `ENROL TIME`,(case `failed_enrollment`.`asn_reason_code` when 1 then 'No enrolment form' when 2 then 'No register group on form' when 3 then 'No course code on form' when 4 then 'Incorrect course code on form' when 5 then 'No waiver code on form' when 6 then 'Invalid course code - W/D' when 7 then 'No learning support group' when 8 then 'No prior quals form' when 9 then 'Incorrect IAG' when 10 then 'Student unsure of course wanted to cancel' when 11 then 'No benefit evidence of fee waiver' when 12 then 'No method of payment' when 13 then 'No adv loan evidence' when 14 then 'Unwilling to pay course fees' when 15 then 'Safeguarding issue' when 16 then 'Immigration issue' when 17 then 'Student enrolled - pressed wrong button' when 18 then 'Student no show - pressed wrong button' when 19 then 'Not an enrolment - ref\'d to as careers' when 20 then 'Student already enrolled' when 21 then 'Not an enrolment - ref\'d to IAG' else 'Other' end) AS `REASON`,`failed_enrollment`.`asn_notes` AS `NOTES`,concat('<button data-revert=\"',`failed_enrollment`.`reg_id`,'\" class=\"secondary button\">Restore</button>') AS `Action` from `failed_enrollment`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_missed_appointments` AS select concat(`queue_missed_appointments`.`reg_first_name`,' ',`queue_missed_appointments`.`reg_last_name`) AS `Enrollee`,date_format(`queue_missed_appointments`.`reg_dob`,'%d/%m/%Y') AS `DOB`,ifnull(`queue_missed_appointments`.`reg_email`,'') AS `Email`,ifnull(`queue_missed_appointments`.`reg_mob`,'') AS `Mobile No`,cast(`queue_missed_appointments`.`reg_created_ts` as time) AS `Registration Time`,timediff(now(),`queue_missed_appointments`.`reg_created_ts`) AS `Waiting Time`,concat('<button data-enrol=\"',`queue_missed_appointments`.`reg_id`,'\" class=\"secondary button\">','Enrolled','</button>','<button data-nos=\"',`queue_missed_appointments`.`reg_id`,'\" class=\"secondary button\">','No Shows','</button>','<button data-revert=\"',`queue_missed_appointments`.`reg_id`,'\" class=\"secondary button\">','Reinstate','</button>') AS `Move To` from `queue_missed_appointments`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dash_no_shows` AS select concat(`no_shows`.`reg_first_name`,' ',`no_shows`.`reg_last_name`) AS `Enrollee`,date_format(`no_shows`.`reg_dob`,'%d/%m/%Y') AS `DOB`,`no_shows`.`reg_email` AS `Email`,`no_shows`.`reg_mob` AS `Mobile No`,cast(`no_shows`.`reg_created_ts` as time) AS `Registration Time`,`no_shows`.`no_show_count` AS `Call count`,cast(`no_shows`.`last_activity_ts` as time) AS `Last Call Time`,concat('<button data-revert=\"',`no_shows`.`reg_id`,'\" class=\"secondary button\">Reinstate</button>','<button data-enrol=\"',`no_shows`.`reg_id`,'\" class=\"secondary button\">Enrolled</button>') AS `Move To` from `no_shows`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `failed_enrollment` AS select `registrations`.`reg_id` AS `reg_id`,`registrations`.`reg_first_name` AS `reg_first_name`,`registrations`.`reg_last_name` AS `reg_last_name`,`registrations`.`reg_dob` AS `reg_dob`,`registrations`.`reg_email` AS `reg_email`,`registrations`.`reg_mob` AS `reg_mob`,`registrations`.`reg_created_ts` AS `reg_created_ts`,`assignments`.`asn_created_ts` AS `asn_created_ts`,`assignments`.`asn_completed_ts` AS `asn_completed_ts`,`assignments`.`asn_notes` AS `asn_notes`,`assignments`.`asn_reason_code` AS `asn_reason_code` from (`registrations` join `assignments`) where ((`assignments`.`asn_reg_id` = `registrations`.`reg_id`) and (`assignments`.`asn_status` = 'FAI'));
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `feed_all_16_to_18` AS select concat(`callouts`.`reg_first_name`,' ',`callouts`.`reg_last_name`,' (',date_format(`callouts`.`reg_dob`,'%d-%b'),')') AS `Message`,concat('Goto ',`callouts`.`src_centre_name`) AS `Status`,`callouts`.`reg_id` AS `reg_id`,`callouts`.`reg_created_ts` AS `reg_created_ts`,`callouts`.`reg_first_name` AS `reg_first_name`,`callouts`.`reg_last_name` AS `reg_last_name`,`callouts`.`reg_dob` AS `reg_dob`,`callouts`.`reg_mob` AS `reg_mob`,-(1) AS `_order_tag` from `callouts` union select concat(`queue_16_to_18`.`reg_first_name`,' ',`queue_16_to_18`.`reg_last_name`,' (',date_format(`queue_16_to_18`.`reg_dob`,'%d-%b'),')') AS `Message`,cast(`queue_16_to_18`.`reg_created_ts` as time) AS `Status`,`queue_16_to_18`.`reg_id` AS `reg_id`,`queue_16_to_18`.`reg_created_ts` AS `reg_created_ts`,`queue_16_to_18`.`reg_first_name` AS `reg_first_name`,`queue_16_to_18`.`reg_last_name` AS `reg_last_name`,`queue_16_to_18`.`reg_dob` AS `reg_dob`,`queue_16_to_18`.`reg_mob` AS `reg_mob`,1 AS `_order_tag` from `queue_16_to_18`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `feed_all_19_plus` AS select concat(`callouts`.`reg_first_name`,' ',`callouts`.`reg_last_name`,' (',date_format(`callouts`.`reg_dob`,'%d-%b'),'rere)') AS `Message`,concat('Goto ',`callouts`.`src_centre_name`) AS `Status`,`callouts`.`reg_id` AS `reg_id`,`callouts`.`reg_created_ts` AS `reg_created_ts`,`callouts`.`reg_first_name` AS `reg_first_name`,`callouts`.`reg_last_name` AS `reg_last_name`,`callouts`.`reg_dob` AS `reg_dob`,`callouts`.`reg_mob` AS `reg_mob`,-(1) AS `_order_tag` from `callouts` union select concat(`queue_19_plus`.`reg_first_name`,' ',`queue_19_plus`.`reg_last_name`,' (',date_format(`queue_19_plus`.`reg_dob`,'%d-%b'),')') AS `Message`,cast(`queue_19_plus`.`reg_created_ts` as time) AS `Status`,`queue_19_plus`.`reg_id` AS `reg_id`,`queue_19_plus`.`reg_created_ts` AS `reg_created_ts`,`queue_19_plus`.`reg_first_name` AS `reg_first_name`,`queue_19_plus`.`reg_last_name` AS `reg_last_name`,`queue_19_plus`.`reg_dob` AS `reg_dob`,`queue_19_plus`.`reg_mob` AS `reg_mob`,1 AS `_order_tag` from `queue_19_plus`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `feed_all_missed_appointments` AS select concat(`callouts`.`reg_first_name`,' ',`callouts`.`reg_last_name`,' (',date_format(`callouts`.`reg_dob`,'%d-%b'),')') AS `Message`,concat('Goto ',`callouts`.`src_centre_name`) AS `Status`,`callouts`.`reg_id` AS `reg_id`,`callouts`.`reg_created_ts` AS `reg_created_ts`,`callouts`.`reg_first_name` AS `reg_first_name`,`callouts`.`reg_last_name` AS `reg_last_name`,`callouts`.`reg_dob` AS `reg_dob`,`callouts`.`reg_mob` AS `reg_mob`,-(1) AS `_order_tag` from `callouts` union select concat(`queue_missed_appointments`.`reg_first_name`,' ',`queue_missed_appointments`.`reg_last_name`,' (',date_format(`queue_missed_appointments`.`reg_dob`,'%d-%b'),')') AS `Message`,cast(`queue_missed_appointments`.`reg_created_ts` as time) AS `Status`,`queue_missed_appointments`.`reg_id` AS `reg_id`,`queue_missed_appointments`.`reg_created_ts` AS `reg_created_ts`,`queue_missed_appointments`.`reg_first_name` AS `reg_first_name`,`queue_missed_appointments`.`reg_last_name` AS `reg_last_name`,`queue_missed_appointments`.`reg_dob` AS `reg_dob`,`queue_missed_appointments`.`reg_mob` AS `reg_mob`,1 AS `_order_tag` from `queue_missed_appointments`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `report_failed` AS select distinct `registrations_archive`.`reg_first_name` AS `Forename`,`registrations_archive`.`reg_last_name` AS `Surname`,`registrations_archive`.`reg_dob` AS `DOB`,ifnull(`registrations_archive`.`reg_email`,'') AS `Email`,ifnull(`registrations_archive`.`reg_mob`,'') AS `Mobile` from (`registrations_archive` join `assignments_archive`) where ((`assignments_archive`.`asn_reg_id` = `registrations_archive`.`reg_id`) and (`assignments_archive`.`asn_status` = 'FAI') and (not(`registrations_archive`.`reg_id` in (select `registrations_archive`.`reg_id` from (`registrations_archive` join `assignments_archive`) where ((`assignments_archive`.`asn_reg_id` = `registrations_archive`.`reg_id`) and (`assignments_archive`.`asn_status` = 'COM'))))));
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `report_no_show` AS select distinct `registrations_archive`.`reg_first_name` AS `Forename`,`registrations_archive`.`reg_last_name` AS `Surname`,`registrations_archive`.`reg_dob` AS `DOB`,ifnull(`registrations_archive`.`reg_email`,'') AS `Email`,ifnull(`registrations_archive`.`reg_mob`,'') AS `Mobile` from (`registrations_archive` join `assignments_archive`) where ((`assignments_archive`.`asn_reg_id` = `registrations_archive`.`reg_id`) and (`assignments_archive`.`asn_status` = 'NOS'));
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `reported_completed` AS select distinct `registrations_archive`.`reg_first_name` AS `Forename`,`registrations_archive`.`reg_last_name` AS `Surname`,`registrations_archive`.`reg_dob` AS `DOB`,ifnull(`registrations_archive`.`reg_email`,'') AS `Email`,ifnull(`registrations_archive`.`reg_mob`,'') AS `Mobile` from (`registrations_archive` join `assignments_archive`) where ((`assignments_archive`.`asn_reg_id` = `registrations_archive`.`reg_id`) and (`assignments_archive`.`asn_status` = 'COM'));
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `summary` AS select (select count(0) from `assignments` where (`assignments`.`asn_status` = 'COM')) AS `enrolled_count`,(select count(0) from `assignments` where (`assignments`.`asn_status` = 'FAI')) AS `failed_enrolled_count`,(select ifnull(ceiling(avg((abs(timestampdiff(SECOND,`assignments`.`asn_completed_ts`,`assignments`.`asn_created_ts`)) / 60))),0) AS `avg_enrolment_mins` from `assignments` where (`assignments`.`asn_completed_ts` is not null)) AS `avg_enrolment_mins`,(select ifnull(ceiling(((15 * (select count(0) from `waiting_list`)) / (select count(0) from `active_service_desks`))),0) AS `avg_wait_time`) AS `avg_wait_mins`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_attendants` AS select concat(`attendants`.`att_first_name`,' ',`attendants`.`att_second_name`) AS `Name`,`attendants`.`att_email` AS `Email`,`attendants`.`att_active` AS `Active`,concat('<button data-att-id=\"',`attendants`.`att_id`,'\" class=\"secondary button\">Edit</button>') AS `Action` from `attendants`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_messages` AS select `rolling_messages`.`rmg_message` AS `Message`,(case `rolling_messages`.`rmg_que_id` when 1 then '16 to 19' when 2 then '19 plus' when 3 then 'Missed Appointments' when 0 then 'No Shows' end) AS `Queue`,`rolling_messages`.`rmg_active` AS `Active`,concat('<button data-rmg-id=\"',`rolling_messages`.`rmg_id`,'\" class=\"secondary button\">Edit</button>','&nbsp;<button data-rmg-id-delete=\"',`rolling_messages`.`rmg_id`,'\" class=\"secondary button\">Delete</button>') AS `Action` from `rolling_messages`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vw_service_desk` AS select `service_desks`.`src_centre_name` AS `Name`,ifnull(`service_desks`.`src_centre_desc`,'') AS `Description`,`service_desks`.`src_active` AS `Active`,concat('<button data-src-id=\"',`service_desks`.`src_id`,'\" class=\"secondary button\">Edit</button>') AS `Action` from `service_desks`;
");
        DB::statement("CREATE OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `waiting_list` AS select `registrations`.`reg_id` AS `reg_id`,`registrations`.`reg_first_name` AS `reg_first_name`,`registrations`.`reg_last_name` AS `reg_last_name`,ifnull(`registrations`.`reg_email`,'') AS `reg_email`,ifnull(`registrations`.`reg_mob`,'') AS `reg_mob`,`registrations`.`reg_dob` AS `reg_dob`,(case when ((select count(0) AS `no_show_count` from `assignments` where ((`assignments`.`asn_status` = 'NOS') and (`assignments`.`asn_reg_id` = `registrations`.`reg_id`))) between 1 and 3) then 3 when ((select count(0) AS `no_show_count` from `assignments` where ((`assignments`.`asn_status` = 'NOS') and (`assignments`.`asn_reg_id` = `registrations`.`reg_id`))) >= (select `config_vars`.`con_value` from `config_vars` where (`config_vars`.`con_name` = 'NO_SHOW_MAX_ATTEMPTS'))) then 0 when (truncate(((to_days(str_to_date(concat(year(curdate()),'-AUG-31'),'%Y-%b-%d')) - to_days(`registrations`.`reg_dob`)) / 365),0) < 19) then 1 when (truncate(((to_days(str_to_date(concat(year(curdate()),'-AUG-31'),'%Y-%b-%d')) - to_days(`registrations`.`reg_dob`)) / 365),0) >= 19) then 2 end) AS `que_id`,(select count(0) AS `no_show_count` from `assignments` where ((`assignments`.`asn_status` = 'NOS') and (`assignments`.`asn_reg_id` = `registrations`.`reg_id`))) AS `no_show_count`,`registrations`.`reg_created_ts` AS `reg_created_ts`,(select ifnull(max(`assignments`.`asn_created_ts`),`registrations`.`reg_created_ts`) from `assignments` where (`assignments`.`asn_reg_id` = `registrations`.`reg_id`)) AS `last_activity_ts` from `registrations` where (not(`registrations`.`reg_id` in (select `assignments`.`asn_reg_id` from `assignments` where ((`assignments`.`asn_status` in ('COM','FAI','STA')) or isnull(`assignments`.`asn_status`))))) order by `registrations`.`reg_created_ts`,(select max(`assignments`.`asn_created_ts`) from `assignments` where (`assignments`.`asn_reg_id` = `registrations`.`reg_id`));
");


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
